# This is a basic workflow to help you get started with Actions

name: Package Resources

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ testing ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #Set mcpack name
      - run: echo "resPackName=wbhs-resources_testing.mcpack" >> $GITHUB_ENV
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Packs contents of src to .mcpack
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          directory: src/
          filename: 'wbhs-resources_testing.mcpack'
          type: zip
      
      #List directory
      - run: |
          ls
          ls src

      #Save pack as Artifact
      - uses: actions/upload-artifact@v2
        with:
          name: mcpack
          path: src/$resPackName
          
      #Create release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: This is an automatic build of the testing branch
          draft: true
          prerelease: true
     
      #Upload texture pack
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: src/$resPackName
          asset_name: $resPackName
          asset_content_type: application/zip
