# This is a basic workflow to help you get started with Actions

name: Package Resources

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ testing ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Packs contents of src to .mcpack
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          directory: src/
          filename: 'wbhs-resources_testing.mcpack'
      
      #List directory
      - run: |
          ls
          ls src
